language: cpp

before_install:
  - sudo apt-get -y install libeigen3-dev python3 python3-pip python3-setuptools

install:
  - pip3 install --user conan cmake numpy
  - sudo bash ./install-libnabo.sh
  
jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      env:
        - GCC_VER="9"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
            - g++-9
            - doxygen
      after_script:
        - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-${GCC_VER}
    - os: linux
      dist: bionic
      compiler: clang
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
      addons: { apt: { packages: ['doxygen'] } }


before_script:
  - eval "${MATRIX_EVAL}"

script:
  - cmake -D ENABLE_COVERAGE:BOOL=TRUE .
  - cmake --build . -- -j2
  - ctest -j2



